import logging
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, HTTPException

from api.routers.common import clear_items_cache
from api.schemas import BlacklistItemRequest, ItemOverrideRequest
from ItemManagement import add_item_to_blacklist, reload_blacklist
from ItemManagement.parse import load_blacklist, add_item_to_whitelist, remove_item_from_whitelist, load_whitelist
from ItemManagement.parse.overrides import load_overrides, save_overrides, validate_override
from config.server_settings import get_server_settings

logger = logging.getLogger(__name__)
router = APIRouter(tags=["blacklist-overrides"])


def _write_runtime_rules_file():
    settings = get_server_settings()
    target = Path(settings.runtime_rules_file)
    target.parent.mkdir(parents=True, exist_ok=True)

    blacklist = set(load_blacklist().get("itemIds", []))
    whitelist = set(load_whitelist().get("itemIds", []))
    overrides = load_overrides()

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    def lua_str(value: str) -> str:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'

    def lua_str_list(items) -> str:
        if not items:
            return "{}"
        entries = ", ".join(lua_str(str(i)) for i in sorted(items))
        return "{ " + entries + " }"

    override_blocks = []
    for override in overrides:
        item_id = override.get("item")
        if not item_id:
            continue
        parts = [f"        id = {lua_str(item_id)}"]
        if override.get("basePrice") is not None:
            parts.append(f"        price = {override['basePrice']}")
        tags = override.get("tags")
        if isinstance(tags, list) and tags:
            tag_list = ", ".join(lua_str(str(t)) for t in tags)
            parts.append(f"        tags = {{ {tag_list} }}")
        stock_range = override.get("stockRange") or {}
        if stock_range.get("min") is not None:
            parts.append(f"        stockMin = {stock_range['min']}")
        if stock_range.get("max") is not None:
            parts.append(f"        stockMax = {stock_range['max']}")
        override_blocks.append("    {\n" + ",\n".join(parts) + ",\n    }")

    overrides_lua = "{\n" + ",\n".join(override_blocks) + "\n}" if override_blocks else "{}"
    blacklist_lua = lua_str_list(blacklist)
    whitelist_lua = lua_str_list(whitelist)

    lua_content = (
        f"-- DynamicTrading Runtime Rules Data\n"
        f"-- Auto-generated by ModManager on {timestamp}\n"
        f"-- DO NOT hand-edit while ModManager is running.\n"
            f"-- Source: DT/MarketSense/Items/MS_RuntimeRules_Data.lua\n"
        f"\n"
        f"return {{\n"
        f"    blacklist = {blacklist_lua},\n"
        f"    whitelist = {whitelist_lua},\n"
        f"    overrides = {overrides_lua},\n"
        f"}}\n"
    )

    target.write_text(lua_content, encoding="utf-8")
    return {"path": str(target), "line_count": lua_content.count("\n")}


@router.get("/api/blacklist")
async def get_blacklist():
    return load_blacklist()


@router.post("/api/blacklist/item")
async def add_blacklist_item(request: BlacklistItemRequest):
    try:
        blacklist = add_item_to_blacklist(request.item_id)
        reload_blacklist()
        sync_info = _write_runtime_rules_file()
        clear_items_cache()
        return {
            "success": True,
            "item_id": request.item_id,
            "blacklist": blacklist,
            "runtime_rules_sync": sync_info,
        }
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        logger.error("Error adding %s to blacklist: %s", request.item_id, exc)
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/api/whitelist")
async def get_whitelist():
    return load_whitelist()


@router.post("/api/whitelist/item")
async def add_whitelist_item(request: BlacklistItemRequest):
    try:
        whitelist = add_item_to_whitelist(request.item_id)
        sync_info = _write_runtime_rules_file()
        clear_items_cache()
        return {
            "success": True,
            "item_id": request.item_id,
            "whitelist": whitelist,
            "runtime_rules_sync": sync_info,
        }
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        logger.error("Error adding %s to whitelist: %s", request.item_id, exc)
        raise HTTPException(status_code=500, detail=str(exc))


@router.delete("/api/whitelist/item/{item_id}")
async def delete_whitelist_item(item_id: str):
    try:
        whitelist = remove_item_from_whitelist(item_id)
        sync_info = _write_runtime_rules_file()
        clear_items_cache()
        return {
            "success": True,
            "item_id": item_id,
            "whitelist": whitelist,
            "runtime_rules_sync": sync_info,
        }
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        logger.error("Error removing %s from whitelist: %s", item_id, exc)
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/api/overrides")
async def get_overrides():
    try:
        overrides = load_overrides()
        return {
            "overrides": overrides,
            "by_item": {override.get("item"): override for override in overrides if override.get("item")},
        }
    except Exception as exc:
        logger.error("Error loading overrides: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc))


@router.put("/api/overrides/item")
async def save_item_override(request: ItemOverrideRequest):
    try:
        override = {"item": request.item_id}
        if request.base_price is not None:
            override["basePrice"] = request.base_price
        if request.tags:
            override["tags"] = request.tags
        if request.stock_min is not None or request.stock_max is not None:
            override["stockRange"] = {}
            if request.stock_min is not None:
                override["stockRange"]["min"] = request.stock_min
            if request.stock_max is not None:
                override["stockRange"]["max"] = request.stock_max
        if request.description:
            override["description"] = request.description

        if len(override) == 1:
            raise HTTPException(status_code=400, detail="Override must include at least one field to save.")

        is_valid, error = validate_override(override)
        if not is_valid:
            raise HTTPException(status_code=400, detail=error or "Invalid override")

        overrides = [entry for entry in load_overrides() if entry.get("item") != request.item_id]
        overrides.append(override)
        save_overrides(overrides)
        sync_info = _write_runtime_rules_file()
        return {
            "success": True,
            "override": override,
            "overrides": overrides,
            "runtime_rules_sync": sync_info,
        }
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Error saving override for %s: %s", request.item_id, exc)
        raise HTTPException(status_code=500, detail=str(exc))


@router.delete("/api/overrides/item/{item_id}")
async def delete_item_override(item_id: str):
    try:
        overrides = load_overrides()
        next_overrides = [entry for entry in overrides if entry.get("item") != item_id]
        if len(next_overrides) == len(overrides):
            raise HTTPException(status_code=404, detail="Override not found")

        save_overrides(next_overrides)
        sync_info = _write_runtime_rules_file()
        return {
            "success": True,
            "item_id": item_id,
            "overrides": next_overrides,
            "runtime_rules_sync": sync_info,
        }
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Error deleting override for %s: %s", item_id, exc)
        raise HTTPException(status_code=500, detail=str(exc))
