from __future__ import annotations

import json
import re
from pathlib import Path


IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
METADATA_LINE_RE = re.compile(r"^--\s*DTM-([A-Za-z0-9]+):\s*(.*?)\s*$")


def render_definition_file(definition: dict[str, object], metadata: dict[str, object] | None = None) -> str:
    body = _render_lua_table(definition, 0)
    return (
        'require "DT/Common/GeolocatorDefinitions/DT_GeolocatorDefinitions"\n\n'
        "DT_GeolocatorSystem = DT_GeolocatorSystem or {}\n\n"
        "DT_GeolocatorSystem.RegisterRegionDefinition("
        f"{body}"
        ")\n"
    )


def write_definition_file(path: Path, definition: dict[str, object], metadata: dict[str, object] | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_definition_file(definition, metadata=metadata), encoding="utf-8")


def parse_generated_metadata(path: Path) -> dict[str, str]:
    metadata: dict[str, str] = {}
    if not path.exists():
        return metadata

    for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not raw_line.startswith("--"):
            break
        match = METADATA_LINE_RE.match(raw_line)
        if not match:
            continue
        metadata[match.group(1)] = match.group(2)
    return metadata


def normalize_generated_content_for_compare(text: str) -> str:
    output_lines: list[str] = []
    for line in str(text).splitlines():
        if line.strip() == "-- Generated by Dynamic Trading Manager. Re-run the Geolocator generator to update this file.":
            continue
        if METADATA_LINE_RE.match(line):
            continue
        output_lines.append(line.rstrip())
    return "\n".join(output_lines).strip() + "\n"


def _render_lua_table(value: object, indent: int) -> str:
    if isinstance(value, dict):
        lines = ["{\n"]
        items = list(value.items())
        for key, item in items:
            lines.append(" " * (indent + 4))
            lines.append(f"{_render_key(key)} = ")
            lines.append(_render_lua_value(item, indent + 4))
            lines.append(",\n")
        lines.append(" " * indent + "}")
        return "".join(lines)
    raise TypeError("Definition root must be a dictionary.")


def _render_lua_value(value: object, indent: int) -> str:
    if isinstance(value, dict):
        return _render_lua_table(value, indent)
    if isinstance(value, list):
        if not value:
            return "{}"
        lines = ["{\n"]
        for item in value:
            lines.append(" " * (indent + 4))
            lines.append(_render_lua_value(item, indent + 4))
            lines.append(",\n")
        lines.append(" " * indent + "}")
        return "".join(lines)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "nil"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)


def _render_key(key: object) -> str:
    text = str(key)
    if IDENTIFIER_RE.match(text):
        return text
    return f"[{json.dumps(text, ensure_ascii=False)}]"
